apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T13:10:37Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "19695"
  uid: ef3797a3-f2ed-445d-b36d-9e73e943d654
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.181.219
  clusterIPs:
  - 10.97.181.219
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31739
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
